version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/zoppy-test/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend/zoppy-test/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # REMOVIDO: network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Cesar1234.
      - DATABASE_NAME=zoppy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
